services:
  - type: web
    name: pybdsite
    env: python
    buildCommand: |
      pip install uv
      uv sync
    startCommand: cd src && uv run gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 60 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0